name: Node.js CI/CD (Heroku)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'prettier.config.js'
      - '.gitignore'
      - '.vscode/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'prettier.config.js'
      - '.gitignore'
      - '.vscode/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'
      - run: npm install
      - run: npm test

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'synonyms-ptbr'
          heroku_email: 'adsonhenriquesilva@gmail.com'
